#@IgnoreInspection BashAddShebang

# Initial cleanup
pebble clean
cargo clean
rm -r rustc_temp

# Get the crate name
crate_name=${PWD##*/}
crate_name=${crate_name//'-'/'_'}

# Build the project through Cargo
cargo --version
cargo build --release || exit 1

cd target/thumbv7m-none-eabi/release/deps

# Move the crates to a different directory, so that the next commands don't remove them.
echo $PWD
mkdir ../crates
mv *.rlib ../crates

# Extract the archive
ar x *.a

# Remove all the mess produced by Rust (shouldn't be a problem if you use the 'compiler-builtins' crate).
find . -type f ! -name '*.rcgu.o' -delete

# Remove the generated object file.
# For some reason, object files generated by Cargo produce a segfault on the 'push' instructions.
rm ${crate_name}*.o

cd -

# Initialize the directories
mkdir rustc_temp

rustc -Vv
# Build the project through rustc
rustc -L target/thumbv7m-none-eabi/release/crates -L target/release/deps --emit=obj --crate-type=staticlib --target thumbv7m-none-eabi src/lib.rs -o rustc_temp/lib.o || exit 1

# Replace the object file we removed earlier with this one
mv rustc_temp/*.o target/thumbv7m-none-eabi/release/deps

# Build through waf
pebble build

# Cleanup
#cargo clean
#rm -r rustc_temp



