#@IgnoreInspection BashAddShebang

# Initial cleanup
pebble clean
cargo clean

# Build the project through Cargo
cargo --version
cargo build --release || exit 1

target="thumbv7m-none-eabi"

cd target/$target/release/deps

# Move the crates to a different directory, so that the next commands don't remove them.
mkdir ../crates
mv *.rlib ../crates

# Extract the archive
ar x *.a

# Remove all the mess produced by Rust (shouldn't be a problem if you use the 'compiler-builtins' crate).
find . -type f ! -name '*.rcgu.o' -delete

# Remove the generated object file.
# For some reason, object files generated by Cargo produce a segfault on the 'push' instructions.
rm hello_world*.o

cd -

# Build the project through rustc
rustc -L target/$target/release/crates -L target/release/deps --emit=obj --crate-type=staticlib --target thumbv7m-none-eabi src/lib.rs -o lib.o || exit 1

# Replace the object file we removed earlier with this one
mv lib.o target/$target/release/deps

# Build through waf
#pebble build

# Cleanup
#cargo clean
#rm -r rustc_temp
